services:
  db:
    image: mysql:latest
    container_name: flashcard-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d/
    networks:
      - flashcard-network

  backend:
    build: ./backend
    container_name: flashcard-backend
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${BACKEND_PORT}:5000"
    depends_on:
      - db
    networks:
      - flashcard-network

  frontend:
    build: ./frontend
    container_name: flashcard-frontend
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - backend
    networks:
      - flashcard-network
    ports:
      - "3000:3000"

volumes:
  db_data:

networks:
  flashcard-network:
